#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const {
  GENERATED_DIR,
  loadBank,
  validateAll,
} = require("./lib/content");

const result = validateAll();
if (result.errors.length > 0) {
  console.error("Build stopped because content validation failed.");
  result.errors.slice(0, 50).forEach((error) => console.error(`- ${error}`));
  process.exit(1);
}

fs.mkdirSync(GENERATED_DIR, { recursive: true });
const catalogOutput = [
  "/* Generated by scripts/build-content.js. Edit content/catalog.json instead. */",
  `window.PRACTICE_CATALOG = ${JSON.stringify(result.catalog)};`,
  "",
].join("\n");
fs.writeFileSync(path.join(GENERATED_DIR, "catalog.js"), catalogOutput);

result.catalog.sections.forEach((section) => {
  const bank = loadBank(section.key);
  const output = [
    "/* Generated by scripts/build-content.js. Edit the canonical JSON bank instead. */",
    "window.PRACTICE_BANKS = window.PRACTICE_BANKS || {};",
    `window.PRACTICE_BANKS[${JSON.stringify(section.key)}] = ${JSON.stringify(bank)};`,
    "",
  ].join("\n");
  fs.writeFileSync(path.join(GENERATED_DIR, `${section.key}.js`), output);
});

console.log(
  `Built ${result.questions.length} validated questions into ${result.catalog.sections.length} banks.`,
);
